//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Submitter.Web.Pages.Submissions {
    
    
    public partial class Sub {
        
        /// <summary>
        /// submission control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Submitter.Web.Controls.Submission submission;
        
        /// <summary>
        /// createCommentControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Submitter.Web.Controls.CreateCommentControl createCommentControl;
        
        /// <summary>
        /// commentViewControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Submitter.Web.Controls.CommentViewControl commentViewControl;
    }
}
