USE [master]
GO
/****** Object:  Database [Submitter]    Script Date: 09/25/2011 05:34:15 ******/
CREATE DATABASE [Submitter] ON  PRIMARY 
( NAME = N'Submitter', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Submitter.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Submitter_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Submitter_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Submitter] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Submitter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Submitter] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Submitter] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Submitter] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Submitter] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Submitter] SET ARITHABORT OFF
GO
ALTER DATABASE [Submitter] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Submitter] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Submitter] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Submitter] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Submitter] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Submitter] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Submitter] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Submitter] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Submitter] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Submitter] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Submitter] SET  DISABLE_BROKER
GO
ALTER DATABASE [Submitter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Submitter] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Submitter] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Submitter] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Submitter] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Submitter] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Submitter] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Submitter] SET  READ_WRITE
GO
ALTER DATABASE [Submitter] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Submitter] SET  MULTI_USER
GO
ALTER DATABASE [Submitter] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Submitter] SET DB_CHAINING OFF
GO
USE [Submitter]
GO
/****** Object:  ForeignKey [FK_tbl_Submission_tbl_User]    Script Date: 09/25/2011 05:34:17 ******/
ALTER TABLE [dbo].[tbl_Submission] DROP CONSTRAINT [FK_tbl_Submission_tbl_User]
GO
/****** Object:  Table [dbo].[tbl_Submission]    Script Date: 09/25/2011 05:34:17 ******/
ALTER TABLE [dbo].[tbl_Submission] DROP CONSTRAINT [FK_tbl_Submission_tbl_User]
GO
DROP TABLE [dbo].[tbl_Submission]
GO
/****** Object:  Table [dbo].[tbl_User]    Script Date: 09/25/2011 05:34:17 ******/
DROP TABLE [dbo].[tbl_User]
GO
/****** Object:  User [SubmitterLogin]    Script Date: 09/25/2011 05:34:15 ******/
DROP USER [SubmitterLogin]
GO
/****** Object:  User [SubmitterLogin]    Script Date: 09/25/2011 05:34:15 ******/
CREATE USER [SubmitterLogin] FOR LOGIN [SubmitterLogin] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[tbl_User]    Script Date: 09/25/2011 05:34:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tbl_User](
	[UserID] [int] NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[Rating] [int] NOT NULL,
 CONSTRAINT [PK_tbl_User] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tbl_Submission]    Script Date: 09/25/2011 05:34:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tbl_Submission](
	[SubmissionID] [int] NOT NULL,
	[Title] [varchar](150) NOT NULL,
	[Link] [varchar](400) NOT NULL,
	[UserID] [int] NOT NULL,
 CONSTRAINT [PK_tbl_Submission] PRIMARY KEY CLUSTERED 
(
	[SubmissionID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  ForeignKey [FK_tbl_Submission_tbl_User]    Script Date: 09/25/2011 05:34:17 ******/
ALTER TABLE [dbo].[tbl_Submission]  WITH CHECK ADD  CONSTRAINT [FK_tbl_Submission_tbl_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[tbl_User] ([UserID])
GO
ALTER TABLE [dbo].[tbl_Submission] CHECK CONSTRAINT [FK_tbl_Submission_tbl_User]
GO
